%% build_WPT_robot_model.m
%  自动创建"值守型光伏清洁机器人无线充电系统"Simulink 仿真模型
%  拓扑：全桥逆变 → 原边 LCC 补偿 → 互感耦合 → 副边 S 补偿 → 全桥整流 → 等效负载
%
%  使用方法：
%    1. 确保 init_WPT_robot.m 在同一文件夹
%    2. 在 MATLAB 命令行运行本脚本：>> build_WPT_robot_model
%    3. 自动生成并打开 WPT_closedloop.slx
%
%  要求：MATLAB R2018b 或更高版本 + Simscape Electrical (Specialized Power Systems)

%% 0. 载入参数
init_WPT_robot;

%% 1. 创建新模型
modelName = 'WPT_closedloop';
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end
if exist([modelName '.slx'], 'file')
    delete([modelName '.slx']);
end
new_system(modelName);
open_system(modelName);

%% 2. 添加 powergui（离散仿真模式）
add_block('powerlib/powergui', [modelName '/powergui'], ...
    'Position', [20 20 120 70], ...
    'SimulationMode', 'Discrete', ...
    'SampleTime', num2str(Ts));

%% ========================================================================
%%  直流电源
%% ========================================================================
add_block('powerlib/Electrical Sources/DC Voltage Source', ...
    [modelName '/Vdc'], ...
    'Position', [80 200 110 260], ...
    'Amplitude', num2str(Vin));

%% ========================================================================
%%  输入电流测量
%% ========================================================================
add_block('powerlib/Measurements/Current Measurement', ...
    [modelName '/Iin_meas'], ...
    'Position', [160 215 190 245]);

%% ========================================================================
%%  全桥逆变（4 个 MOSFET + 2 路 PWM）
%% ========================================================================
% --- Q1（左上）---
add_block('powerlib/Power Electronics/Mosfet', ...
    [modelName '/Q1'], ...
    'Position', [280 160 310 210]);
% --- Q3（左下）---
add_block('powerlib/Power Electronics/Mosfet', ...
    [modelName '/Q3'], ...
    'Position', [280 290 310 340]);
% --- Q2（右上）---
add_block('powerlib/Power Electronics/Mosfet', ...
    [modelName '/Q2'], ...
    'Position', [400 160 430 210]);
% --- Q4（右下）---
add_block('powerlib/Power Electronics/Mosfet', ...
    [modelName '/Q4'], ...
    'Position', [400 290 430 340]);

% --- PWM 信号 1（驱动 Q1, Q4）---
add_block('simulink/Sources/Pulse Generator', ...
    [modelName '/PWM1'], ...
    'Position', [180 100 220 130], ...
    'Period', num2str(Tpwm), ...
    'PulseWidth', '50', ...
    'PhaseDelay', num2str(phase1), ...
    'Amplitude', '1');

% --- PWM 信号 2（驱动 Q2, Q3，相位差 180°）---
add_block('simulink/Sources/Pulse Generator', ...
    [modelName '/PWM2'], ...
    'Position', [180 370 220 400], ...
    'Period', num2str(Tpwm), ...
    'PulseWidth', '50', ...
    'PhaseDelay', num2str(phase2), ...
    'Amplitude', '1');

%% ========================================================================
%%  原边 LCC 补偿网络
%% ========================================================================
% Lf：串联电感
add_block('powerlib/Elements/Series RLC Branch', ...
    [modelName '/Lf'], ...
    'Position', [500 200 550 250], ...
    'BranchType', 'L', ...
    'Inductance', num2str(Lf));

% Cf：并联电容（连接在 Lf 输出与回流母线之间）
add_block('powerlib/Elements/Series RLC Branch', ...
    [modelName '/Cf'], ...
    'Position', [600 280 650 330], ...
    'BranchType', 'C', ...
    'Capacitance', num2str(Cf));

% C1：串联补偿电容
add_block('powerlib/Elements/Series RLC Branch', ...
    [modelName '/C1'], ...
    'Position', [680 200 730 250], ...
    'BranchType', 'C', ...
    'Capacitance', num2str(C1));

%% ========================================================================
%%  互感耦合线圈
%% ========================================================================
add_block('powerlib/Elements/Mutual Inductance', ...
    [modelName '/MutualInd'], ...
    'Position', [800 180 880 300], ...
    'SelfImpedanceL1', ['[' num2str(R1) ' ' num2str(L1) ']'], ...
    'SelfImpedanceL2', ['[' num2str(R2) ' ' num2str(L2) ']'], ...
    'MutualImpedance', num2str(M));

%% ========================================================================
%%  副边 S 补偿（C2）
%% ========================================================================
add_block('powerlib/Elements/Series RLC Branch', ...
    [modelName '/C2'], ...
    'Position', [950 200 1000 250], ...
    'BranchType', 'C', ...
    'Capacitance', num2str(C2));

%% ========================================================================
%%  全桥整流（二极管桥）
%% ========================================================================
add_block('powerlib/Power Electronics/Universal Bridge', ...
    [modelName '/Rectifier'], ...
    'Position', [1080 180 1150 300], ...
    'Arms', '2', ...
    'PowerElectronicDevice', 'Diodes');

%% ========================================================================
%%  输出滤波电容
%% ========================================================================
add_block('powerlib/Elements/Series RLC Branch', ...
    [modelName '/Co'], ...
    'Position', [1220 250 1270 300], ...
    'BranchType', 'C', ...
    'Capacitance', num2str(Co));

%% ========================================================================
%%  等效负载
%% ========================================================================
add_block('powerlib/Elements/Series RLC Branch', ...
    [modelName '/RL'], ...
    'Position', [1320 200 1370 300], ...
    'BranchType', 'R', ...
    'Resistance', num2str(RL));

%% ========================================================================
%%  输出电压、电流测量
%% ========================================================================
add_block('powerlib/Measurements/Voltage Measurement', ...
    [modelName '/Vo_meas'], ...
    'Position', [1420 220 1450 260]);

add_block('powerlib/Measurements/Current Measurement', ...
    [modelName '/Io_meas'], ...
    'Position', [1200 190 1230 220]);

%% ========================================================================
%%  测量与运算子系统
%% ========================================================================
% 输入电压测量
add_block('powerlib/Measurements/Voltage Measurement', ...
    [modelName '/Vin_meas'], ...
    'Position', [80 300 110 340]);

% --- Product 模块：计算功率 ---
add_block('simulink/Math Operations/Product', ...
    [modelName '/Pin_calc'], ...
    'Position', [200 450 240 480]);
add_block('simulink/Math Operations/Product', ...
    [modelName '/Pout_calc'], ...
    'Position', [1500 450 1540 480]);

% --- Mean 模块（Moving Average 用 Discrete Mean 近似）---
add_block('simulink/Math Operations/Divide', ...
    [modelName '/Eff_calc'], ...
    'Position', [800 440 840 480]);

% --- Scope ---
add_block('simulink/Sinks/Scope', ...
    [modelName '/Scope_Power'], ...
    'Position', [900 440 940 480], ...
    'NumInputPorts', '3');

% --- To Workspace ---
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/ToWS_Pin'], ...
    'Position', [300 450 360 470], ...
    'VariableName', 'Pin_ws', ...
    'SaveFormat', 'Timeseries');
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/ToWS_Pout'], ...
    'Position', [1600 450 1660 470], ...
    'VariableName', 'Pout_ws', ...
    'SaveFormat', 'Timeseries');
add_block('simulink/Sinks/To Workspace', ...
    [modelName '/ToWS_eta'], ...
    'Position', [900 500 960 520], ...
    'VariableName', 'eta_ws', ...
    'SaveFormat', 'Timeseries');

%% ========================================================================
%%  连线（核心电力回路）
%% ========================================================================
% 注意：Simulink 脚本连线比较长，这里列出主要电力通路。
% 由于端口名在不同 MATLAB 版本可能略有差异，这里用 try-catch 包裹。
% 如果连线失败，手动连接即可——模块位置已经排好。

try
    % Vdc+ → Iin_meas → Q1 drain (正母线)
    add_line(modelName, 'Vdc/1', 'Iin_meas/1', 'autorouting','smart');
    add_line(modelName, 'Iin_meas/1', 'Q1/1', 'autorouting','smart');
    
    % Q1 source = Q3 drain = 桥臂 A 中点 → Lf
    add_line(modelName, 'Q1/2', 'Lf/1', 'autorouting','smart');
    add_line(modelName, 'Q3/1', 'Q1/2', 'autorouting','smart');
    
    % Q2 drain = 正母线
    add_line(modelName, 'Iin_meas/1', 'Q2/1', 'autorouting','smart');
    % Q2 source = Q4 drain = 桥臂 B 中点（回流）
    add_line(modelName, 'Q4/1', 'Q2/2', 'autorouting','smart');
    
    % Q3 source = Q4 source = Vdc- (负母线)
    add_line(modelName, 'Q3/2', 'Vdc/2', 'autorouting','smart');
    add_line(modelName, 'Q4/2', 'Vdc/2', 'autorouting','smart');
    
    % PWM 驱动
    add_line(modelName, 'PWM1/1', 'Q1/3', 'autorouting','smart');
    add_line(modelName, 'PWM1/1', 'Q4/3', 'autorouting','smart');
    add_line(modelName, 'PWM2/1', 'Q2/3', 'autorouting','smart');
    add_line(modelName, 'PWM2/1', 'Q3/3', 'autorouting','smart');
    
    % Lf → (节点) → Cf(并联到桥臂B中点) 和 C1(串联)
    add_line(modelName, 'Lf/2', 'C1/1', 'autorouting','smart');
    add_line(modelName, 'Lf/2', 'Cf/1', 'autorouting','smart');
    add_line(modelName, 'Cf/2', 'Q2/2', 'autorouting','smart');  % Cf 另一端接桥臂B
    
    % C1 → Mutual Inductance 原边
    add_line(modelName, 'C1/2', 'MutualInd/1', 'autorouting','smart');
    add_line(modelName, 'MutualInd/2', 'Q2/2', 'autorouting','smart'); % L1 回流
    
    % Mutual Inductance 副边 → C2
    add_line(modelName, 'MutualInd/3', 'C2/1', 'autorouting','smart');
    
    % C2 → 整流桥 AC 输入
    add_line(modelName, 'C2/2', 'Rectifier/1', 'autorouting','smart');
    add_line(modelName, 'MutualInd/4', 'Rectifier/2', 'autorouting','smart');
    
    % 整流桥 DC 输出 → Io_meas → Co//RL
    add_line(modelName, 'Rectifier/3', 'Io_meas/1', 'autorouting','smart');
    add_line(modelName, 'Io_meas/2', 'RL/1', 'autorouting','smart');
    add_line(modelName, 'Io_meas/2', 'Co/1', 'autorouting','smart');
    add_line(modelName, 'RL/2', 'Rectifier/4', 'autorouting','smart');
    add_line(modelName, 'Co/2', 'Rectifier/4', 'autorouting','smart');
    
    % 输出电压测量
    add_line(modelName, 'Io_meas/2', 'Vo_meas/1', 'autorouting','smart');
    add_line(modelName, 'Rectifier/4', 'Vo_meas/2', 'autorouting','smart');
    
    fprintf('✓ 主回路连线完成\n');
catch ME
    fprintf('⚠ 部分连线未成功（端口名版本差异），请手动补连。\n');
    fprintf('  错误信息：%s\n', ME.message);
end

%% ========================================================================
%%  配置仿真参数
%% ========================================================================
set_param(modelName, ...
    'StopTime', '0.005', ...           % 5 ms
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(Ts));

%% ========================================================================
%%  保存模型
%% ========================================================================
save_system(modelName);
fprintf('\n========================================\n');
fprintf('  模型 "%s.slx" 创建成功！\n', modelName);
fprintf('  仿真时间：5 ms | 步长：%.0e s\n', Ts);
fprintf('  请在模型中检查连线，然后点击 Run。\n');
fprintf('========================================\n');
